#!/usr/bin/env bash

set -e

ISO=$(curl -4 --max-time 10 ifconfig.co/country-iso || echo "US")
timedatectl set-ntp true

echo -e "\n-------- Updating Keyring --------\n"
pacman -Sy --noconfirm archlinux-keyring

# Make sure reflector is/gets installed.
echo -e "\n==> Installing Reflector"
pacman -Sy --noconfirm --needed reflector rsync

if [[ -f /etc/pacman.d/mirrorlist.backup ]]; then
    echo -e "\n==> Mirror list already backed up."
else
    cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
    echo -e "\n==> Backed up mirror list."
fi

echo -e "\n==> Fetching the fastest 6 mirrors for country: $ISO"
if ! reflector --country "$ISO" --age 6 --fastest 6 --sort rate --save /etc/pacman.d/mirrorlist; then
    echo "Error: Failed to fetch mirrors."
    exit 1
fi
